spring:
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: http://localhost:9000
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-admin/${segment}
