# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\"-\n\x08Response\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t23\n\x0b\x46ileService\x12$\n\rloadAlgorithm\x12\x08.Request\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RESPONSE']._serialized_start=14
  _globals['_RESPONSE']._serialized_end=59
  _globals['_REQUEST']._serialized_start=61
  _globals['_REQUEST']._serialized_end=87
  _globals['_FILESERVICE']._serialized_start=89
  _globals['_FILESERVICE']._serialized_end=140
# @@protoc_insertion_point(module_scope)
